version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: aws_mysql
    environment:
      MYSQL_ROOT_PASSWORD: aws-intern-2023
      MYSQL_DATABASE: aws-intern
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:

